title: La increible pagina de GitHub Pages
author: JesusTics
email: L181061259@mulege.tecnm.mx
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Esta pagina sera la que se estara utilizando a lo largo de este curso
  Espero les guste

# social links
twitter_username: JesusTics # DO NOT include the @ character, or else the build will fail!
github_username:  JessuTics # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
